### ISSUE TITLE
Add a way to specify a different certificate lifetime

### ISSUE THREAD

**Issue by david-guenault** [cloudpipe/keymaster#2]
It's currently hardcoded to 1 year.

**Comment by smashwilson** [comment]
:+1: Another getopts argument, probably?

**Comment by smashwilson** [comment]
Also, I do want to be careful not to try to build a full-on OpenSSL wrapper, by the way -- my main use case is for "quickly generate a set of **development** certificates."

Actually, I should note that in the README, too.

**Comment by david-guenault** [comment]
OK, Thx ! ;-)
